### PR TITLE
Add bTag scale factor factory

### PR DESCRIPTION
**Pull request by BlancoFS**

### CODE REVIEW

**Comment by mlizzo** [comment]
Hi @BlancoFS thanks for the nice additions you made! I have a few comments:
- I noticed that you pushed btagging json files as well, are those the ones centrally provided by the BTV group, right? If so, I think we could simply take them from [this other PR](https://github.com/latinos/mkShapesRDF/pull/44/files#diff-043df5bdbf6639d7a77e1d44c5226fd7371e5259a1e4df3a0dd5d64c30dca44fR83-R84) you just made, no need to upload them twice
- I'm not sure I understand how you are computing SFs when the "light" mode is selected. As far as I know, the `algo_light` and `algo_mujets` sets are fixed WP SFs for light and b/c jets, respectively, and you have to evaluate the b-tagging efficiency on MC in order to apply these SFs properly (see [here](https://btv-wiki.docs.cern.ch/PerformanceCalibration/fixedWPSFRecommendations/)). Are MC efficiencies computed somewhere else?
- Related to the bullet above, BTV added XT and XXT WPs in Run3, which might be worth exploring, since such extra-(extra-)tight selections should further reduce the ttbar background in our signal regions

**Comment by BlancoFS** [comment]
Ciao @mlizzo, thank you for the comments!

First, about the json files. You are right, it's a best procedure to point directly to the jsonpog-integration folder that is downloaded during the installation than storing the json files directly on the FW. Thank for pointing it out, I will modify that.

Second point, you are also right. To be honest, I only translated the old bTagSFProducer to RDF. What I noticed is that, as you said, MC efficiencies are needed to properly compute the fixed WP scale factors so it does not really make sense to do it during the post-processing. In fact, if you take a look to `Steps_cfg.py` (both on mkShapesRDF and LatinoAnalysis) the fixed WP scale factors are never run. Only the shape SF piece of code is run at the end. I would propose to remove the fixed WP part of the module.

Third. I am not sure if a the XT and XXT working points would reduce the ttbar background, but the opposite. Usually, we use the L working point as our 'tighter' WP. A further reduction of the ttbar contamination would come from a `XL` WP not from `XT`, right?

**Comment by mlizzo** [comment]
Hi @BlancoFS , I've clearly swapped the logic about b-tagging and bjet rejection, forget about my last comment, sorry for the noise. About the second bullet, we could either pre-compute MC efficiencies through a pretty standard and generic ww->2l2nu selection, such that these efficiencies could be stored in some root files and then called when running this step, or, like you said, simply skip this part and delegate it to each analyser. I did implement the code for doing this a few months ago, eventually we can recycle that and adapt it to this module, if needed

**Comment by BlancoFS** [comment]
I don't have any strong opinion in storing the fixed WP SF or leave the task to the analyzers. I would say that comuting fixed WP SF on-the-fly is not a bad option since it's not very expensive in terms of computing. As you prefer

**Comment by mlizzo** [comment]
Sure, fine by me too, we could then remove unused lines

**Comment by NTrevisani** [comment]
Hi @BlancoFS and @mlizzo, thank you for the careful review of this module. I agree we can compute the fixed WP scale factors on-the-fly. If you think everything looks ok, I will merge this module.

**Pull request merged**
